Fix `mod_auth_openidc` parameters
A typo in the data type cause an exception with recent Puppet 8
versions:

```
Error: The key '["IDTokenEncryptedResponseAlg"]' is declared more than once (file: /etc/puppetlabs/code/environments/production/modules/apache/types/oidcsettings.pp, line: 41, column: 57) on node b4d45d8831d5.mtgrj3ika5nejlcpzgeeecg0la.cx.internal.cloudapp.net
```

According to the upstream repository configuration file, this is a
copy-paste error.