fix duplicate definition of auth_basic-mod
PR 2252 breaks the usage of auth_basic in a vhost, because the module is
declared twice:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Apache::Mod[auth_basic] is already declared at (file: /etc/puppetlabs/code/environments/module_updates/modules/apache/manifests/default_mods.pp, line: 142); cannot redeclare (file: /etc/puppetlabs/code/environments/module_updates/modules/apache/manifests/mod/auth_basic.pp, line: 7) (file: /etc/puppetlabs/code/environments/module_updates/modules/apache/manifests/mod/auth_basic.pp, line: 7, column: 3) (file: /etc/puppetlabs/code/environments/module_updates/site-modules/rx_apache/manifests/vhost.pp, line: 336) on node ...

fix it by including the appropriate class in defaults_mods, instead of
just defining the module